[package]
name = "traceability-log"
version = "0.1.0"
edition = "2021"
authors = ["VineFi Team"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "23.0.1" }

[dev-dependencies]
soroban-sdk = { version = "23.0.1", features = ["testutils"] }
